spring.main.allow-circular-references = true
# sql config
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
spring.devtools.livereload.port=35730
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect


spring.boot.admin.client.url=http://localhost:8888
management.endpoints.web.exposure.include=*

# 传输的最大文件限制
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=0
# 传输的最大文件限制
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

