server:
  port: 8080

spring:
  datasource:
    dynamic:
      primary: jcxx
      strict: false
      lazy: true
      datasource:
        jcxx:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/jcxx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: root
        gcdd:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/gcdd?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: root
  redis:
    host: localhost
    port: 6379
    database: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.szy.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.szy: debug